// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBabHuNGWYOnHchjugGOpGMEFOATzOgow',
    appId: '1:585338984125:web:8e4a70019f29ec9fcb09d4',
    messagingSenderId: '585338984125',
    projectId: 'gifty-806f1',
    authDomain: 'gifty-806f1.firebaseapp.com',
    storageBucket: 'gifty-806f1.appspot.com',
    measurementId: 'G-XZLZ5YW77Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlRT1dSlwKffwqTFFNhsNrQLHsjqN94Ek',
    appId: '1:585338984125:android:714556edd589e000cb09d4',
    messagingSenderId: '585338984125',
    projectId: 'gifty-806f1',
    storageBucket: 'gifty-806f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLeBiq7teZ87nhCVL_VsR5IbyUTFQr6eU',
    appId: '1:585338984125:ios:5b3b3e667c4190d2cb09d4',
    messagingSenderId: '585338984125',
    projectId: 'gifty-806f1',
    storageBucket: 'gifty-806f1.appspot.com',
    iosClientId: '585338984125-233bm1d7s45k5iilnbqv5k9kukvfm73v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gifty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLeBiq7teZ87nhCVL_VsR5IbyUTFQr6eU',
    appId: '1:585338984125:ios:5b3b3e667c4190d2cb09d4',
    messagingSenderId: '585338984125',
    projectId: 'gifty-806f1',
    storageBucket: 'gifty-806f1.appspot.com',
    iosClientId: '585338984125-233bm1d7s45k5iilnbqv5k9kukvfm73v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gifty',
  );
}
